#!/bin/bash

./xrun < santorini.rc/1-in.json | diff - santorini.rc/1-out.json
./xrun < santorini.rc/2-in.json | diff - santorini.rc/2-out.json
./xrun < santorini.rc/3-in.json | diff - santorini.rc/3-out.json
./xrun < santorini.rc/4-in.json | diff - santorini.rc/4-out.json
./xrun < santorini.rc/5-in.json | diff - santorini.rc/5-out.json

