#!/bin/bash

./xrules < rules-tests/1-in.json | diff - rules-tests/1-out.json 
./xrules < rules-tests/2-in.json | diff - rules-tests/2-out.json 
./xrules < rules-tests/3-in.json | diff - rules-tests/3-out.json 
./xrules < rules-tests/4-in.json | diff - rules-tests/4-out.json 
./xrules < rules-tests/5-in.json | diff - rules-tests/5-out.json 
