#!/bin/bash

./xstrategy < strategy-tests/1-in.json | diff - strategy-tests/1-out.json 
./xstrategy < strategy-tests/2-in.json | diff - strategy-tests/2-out.json 
./xstrategy < strategy-tests/3-in.json | diff - strategy-tests/3-out.json 
./xstrategy < strategy-tests/4-in.json | diff - strategy-tests/4-out.json 
./xstrategy < strategy-tests/5-in.json | diff - strategy-tests/5-out.json 
